package traefik

import (
	"fmt"
	"os"
	"path/filepath"

	"gopkg.in/yaml.v3"
)

// GenerateOverride creates a Docker Compose override file with Traefik priority labels.
// It parses the user's compose file to find services and checks for existing priority labels.
// Returns the path to the generated override file.
func GenerateOverride(worktreePath string, priority int64) (string, error) {
	// Read user's compose file
	composePath := filepath.Join(worktreePath, "docker-compose.yml")
	data, err := os.ReadFile(composePath)
	if err != nil {
		return "", fmt.Errorf("failed to read compose file: %w", err)
	}

	// Parse compose YAML
	var compose struct {
		Services map[string]interface{} `yaml:"services"`
	}
	if err := yaml.Unmarshal(data, &compose); err != nil {
		return "", fmt.Errorf("failed to parse compose file: %w", err)
	}

	// Check for existing Traefik priority labels
	for serviceName, serviceConfig := range compose.Services {
		if service, ok := serviceConfig.(map[string]interface{}); ok {
			if labels, ok := service["labels"]; ok {
				if labelMap, ok := labels.(map[string]interface{}); ok {
					for labelKey := range labelMap {
						// Check if this is a priority label for the service's router
						// Format: traefik.http.routers.<name>.priority
						if isPriorityLabel(labelKey) {
							return "", fmt.Errorf("existing Traefik priority label found: %s (service: %s). "+
								"Please remove existing priority labels or disable Traefik routing for this project",
								labelKey, serviceName)
						}
					}
				}
			}
		}
	}

	// Build override file content
	overrideContent := fmt.Sprintf("# Generated by OtterStack for priority-based routing\n")
	overrideContent += fmt.Sprintf("# Priority: %d\n", priority)
	overrideContent += "services:\n"

	// Add priority labels for each service
	for serviceName := range compose.Services {
		// Use the service name as the router name (common convention)
		// Label format: traefik.http.routers.<service>.priority
		overrideContent += fmt.Sprintf("  %s:\n", serviceName)
		overrideContent += fmt.Sprintf("    labels:\n")
		overrideContent += fmt.Sprintf("      - \"traefik.http.routers.%s.priority=%d\"\n",
			serviceName, priority)
	}

	// Write override file
	overridePath := filepath.Join(worktreePath, "docker-compose.traefik.yml")
	if err := os.WriteFile(overridePath, []byte(overrideContent), 0644); err != nil {
		return "", fmt.Errorf("failed to write override file: %w", err)
	}

	return overridePath, nil
}

// isPriorityLabel checks if a label key is a Traefik priority label.
func isPriorityLabel(labelKey string) bool {
	// Check if the label ends with ".priority"
	// Format: traefik.http.routers.<name>.priority
	return len(labelKey) > 9 && labelKey[len(labelKey)-9:] == ".priority"
}
